version: 2
jobs:
  build_sample:
      docker:
        - image: zcobell/adcirc_20170924 
      steps:
        - checkout
        - run: 
            name: Configure model
            command: mkdir build; cd build; cmake .. ; make
        - run: 
            name: Run model
            command: cd build ; ./model
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_sample
